spring:
  datasource:
    url: jdbc:mysql://192.168.43.164:3306/test?useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  rabbitmq:
    host: 192.168.43.164
    port: 5672
    username: admin
    password: admin
  mvc:
    view:
      prefix: /html
      suffix: .html

# size（上传文件大小限制，单位/KB）
uploadfile:
  size: 20480
  type: jpg,png,ico,bmp,jpeg,doc,docx,xls,xlsx,ppt,pptx,pdf,mp4,war
  path: /data/upload
